default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: rails-services-sandbox_development

test:
  <<: *default
  database: rails-services-sandbox_test

production:
  <<: *default
  database: rails-services-sandbox_production
  username: rails-services-sandbox
  password: <%= ENV['RAILS-SERVICES-SANDBOX_DATABASE_PASSWORD'] %>
